---
- name: Déployer Longhorn (Stockage)
  hosts: localhost
  gather_facts: no

  tasks:
    - name: "S'assurer que le namespace 'longhorn-system' existe"
      kubernetes.core.k8s:
        name: longhorn-system
        api_version: v1
        kind: Namespace
        state: present

    - name: "Ajouter le Chart Repo de Longhorn"
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
        state: present

    - name: "Déployer Longhorn depuis le Chart Helm"
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        state: present
        wait: true # Attendre que le déploiement soit terminé
        timeout: 600s # 10 minutes