---
# Playbook principal pour l'installation

- name: Déployer les outils Cloud Native
  hosts: localhost
  gather_facts: no

  tasks:
    - name: "TEST : Vérifier que le Kubeconfig est trouvé"
      ansible.builtin.command: kubectl config current-context
      register: context
      changed_when: false # Ne pas marquer comme "changé"

    - name: "Afficher le contexte K8s"
      ansible.builtin.debug:
        var: context.stdout

# Importer le playbook Longhorn
- import_playbook: playbooks/longhorn.yaml

# Importer le playbook ArgoCD
- import_playbook: playbooks/argocd.yaml